server:
  port: 8000
spring:
  application:
    name: ams
  thymeleaf:
    prefix: classpath:/template/
eureka:
  client:
    healthcheck:
        enabled: true
    serviceUrl:
      defaultZone: http://wzb:123456@localhost:8761/eureka
  instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name} @ ${spring.cloud.client.ipAddress}:${server.port}
